---
collections:
  - name: amazon.aws
    version: 7.6.1
    source: https://galaxy.ansible.com
  - name: ansible.netcommon
    version: 5.3.0
    source: https://galaxy.ansible.com
  - name: ansible.posix
    version: 1.6.2
    source: https://galaxy.ansible.com
  - name: ansible.utils
    version: 2.12.0
    source: https://galaxy.ansible.com
  - name: awx.awx
    version: 23.9.0
    source: https://galaxy.ansible.com
  - name: community.aws
    version: 7.2.0
    source: https://galaxy.ansible.com
  - name: community.crypto
    version: 2.22.3
    source: https://galaxy.ansible.com
  - name: community.dns
    version: 2.9.8
    source: https://galaxy.ansible.com
  - name: community.docker
    version: 3.13.3
    source: https://galaxy.ansible.com
  - name: community.general
    version: 8.6.8
    source: https://galaxy.ansible.com
  - name: community.library_inventory_filtering_v1
    version: 1.0.2
    source: https://galaxy.ansible.com
  - name: community.network
    version: 5.1.0
    source: https://galaxy.ansible.com
  - name: community.zabbix
    version: 4.1.1
    source: https://galaxy.ansible.com
  - name: netapp.aws
    version: 21.7.1
    source: https://galaxy.ansible.com
  - name: sophos.sophos_firewall
    version: 1.4.1
    source: https://galaxy.ansible.com
  - name: theforeman.foreman
    version: 3.15.0
    source: https://galaxy.ansible.com
...
